pages:
  - name: Video Info
    modules:
    - title: $mpv.title
      type: text
      icon: theaters

    -
      - title: $mpv.progress_text
        type: progress
        value: $mpv.pos_percent
        icon:  $mpv.icon_play_pause

      - title: $mpv.progress_text
        type: progress
        value: $mpv.pos_percent
        icon:  $mpv.icon_play_pause

    - title: $mpv.volume
      type: progress
      value: $mpv.volume_percent
      icon: volume-up

  - name: Video Control
    modules:
      - type: buttons
        buttons:
          - icon: fast-rewind
            action: mpv.seek_back

          - icon: $mpv.icon_play_pause
            action: mpv.pause

          - icon: fast-forward
            action: mpv.seek_fwd
# - type: buttons
#   buttons:
#     - icon: fast-rewind
#       action: mpv.seek_back
#
#     - icon: $mpv.icon_play_pause
#       action: mpv.pause
#
#     - icon: fast-forward
#       action: mpv.seek_fwd
#
# - type: buttons
#   buttons:
#     - icon: fullscreen
#       action: mpv.fullscreen
#
#     - icon: short-text
#       action: mpv.show_progress
#
#     - icon: short-text
#       action: mpv.fun
#
# - type: buttons
#   buttons:
#     - icon: volume-down
#       action: mpv.volume_down
#
#     - icon: volume-mute
#       action: mpv.mute
#
#     - icon: volume-up
#       action: mpv.volume_up
